### PR TITLE
consider plugins that end with numbers

### PR DESCRIPTION
**Pull request by kraftner**
...like contact-form-7

`contact-form-7.1.2.3.zip` got picked up as version `7.1.2`

### CODE REVIEW

**Comment by Rarst** [comment]
Patch doesn't seem to improve it?

``` php
preg_match( '|\.((?:\d+\.*){1,3})|', 'contact-form-7.1.2.3.zip', $matches );
var_dump( $matches );
// array(2) { [0]=> string(7) ".1.2.3." [1]=> string(6) "1.2.3." }
```

**Comment by kraftner** [comment]
``` php
$parts = preg_split('|\.((?:\d+\.*){1,3})|', 'contact-form-7.1.2.3.zip', 2, PREG_SPLIT_DELIM_CAPTURE);
var_dump($parts);
// array(3) { [0]=> string(14) "contact-form-7" [1]=> string(6) "1.2.3." [2]=> string(3) "zip" } 
```

**Comment by Rarst** [comment]
My point was that 1.2.3 isn't really valid version for it either.

**Comment by Rarst** [comment]
Wait! I just got it. 7 is part of plugin's name. My brain was treating it as 4 digit version. Which would break in either case.

**Comment by kraftner** [comment]
Oh sorry if I didn't make that clear enough. Have it in the title.

The new regex checks that before the first number is a dot which doesn't happen if a number is in the plugin name.

**Comment by Rarst** [comment]
It wasn't my assumption really that version is separated from name with a dot necessarily. I am just trying to look for semantic version and take whatever is before and after.

**Comment by kraftner** [comment]
Okay I just derived that assumption from the Readme. Any other suggestion? It is just that any number in the name breaks it now.

**Comment by Rarst** [comment]
The issue with this specific Contact Form 7 thing is that it's part of name in _this_ case, but it might be 4 digit version in other. It's an edge case and it's hard to think about edge case, when I don't think the normal cases are ironed out sufficiently.

**Comment by kraftner** [comment]
Okay I get that.
But as you haven't really established a naming convention for the files yet maybe just use another separator?

```
name-1--1.2.3.4.zip
```

Or even stop using the filename and have package and version as folders while only using the first file in that folder?

```
vendor/package/version/randomfilename.zip
```

**Comment by Rarst** [comment]
I hadn't established convention, because I don't _want_ to make one. I want people just to be able to throw whatever archives they have on it. And it work as long as format it _reasonably_ same – that is name, followed by version, followed by extension.

**Comment by kraftner** [comment]
Okay I get it. I'll close then.

**Comment by Rarst** [comment]
To be clear, regex _does_ need improvement. It just needs much _more_ improvement than forcing specific separator on people. For example 1 digit per semver part is already bad assumption.

I'll need to collect more cases like this and put together a test setup...

PS no, actually it should match multiple digits, that was incorrect.

**Pull request closed without merging**
