### PR TITLE
Add https detection

### PR DESCRIPTION
**Pull request by grappler**
As composers new default is to use HTTPS then https detection is needed.

### CODE REVIEW

**Comment by Rarst** [comment]
Hmmm... What if someone running on port other than default? This looks like it will just break.

I think there was a service in Silex for URL generation. If it suits the need we should probably just make use of that. Will try to take a look, just coming back from vacation and sick on top :(

**Comment by grappler** [comment]
I am not sure they could use another port. If they did then the sympony fuunction [`getHttpHost()`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1030-L1040) would fail too.

**Comment by Rarst** [comment]
Why would it fail? It's clearly written to handle non-default ports. Anyway if we can dump generation on service it will be better than managing by hand in any case.

**Comment by grappler** [comment]
Ah, sorry I misread the code. I have updated the PR with slightly better solution. Let me know what you think.

**Comment by Rarst** [comment]
Sorry for taking my time to get to this. :) It was a busy month, coming out of vacation and sickness on top.

I committed an alternate take, using UrlGenerator (as mentioned above), in https://github.com/Rarst/release-belt/commit/6baf895c0de7b8c291f2de44505d9de3d6544cee

I think long term that better abstracts away those URLs and probably brings project closer to be able run out of subfolders, as opposed to site root.

Please test and let me know if it works well for you! I don't have SSL install on hand right now.

**Comment by grappler** [comment]
Yes, it looks to work fine. Thanks

**Pull request closed without merging**
