### PR TITLE
Support `composer/installers` 2.x, in addition to the 1.x.

### PR DESCRIPTION
**Pull request by grappler**
Similar to what has been done on WPackagist https://github.com/outlandishideas/wpackagist/pull/420

https://github.com/composer/installers/releases/tag/v2.0.0

### CODE REVIEW

**Comment by Rarst** [comment]
This is actually... Not straightforward for the purposes of Belt-generated Composer data.

Installers 2.0 took the major version opportunity to remove support for bunch of types. So allowing 2.x on those could very well end up in a state where package gets installers version that does not support the package's type.

And vice versa, any type added only in 2.x going forward (I don't get the impression there is intent to maintain parity?) might get installed with 1.x and no support for it.

**Comment by grappler** [comment]
Ah, yes, I forgot that `release-belt` can be used for any types and not just for WordPress types.

**Comment by Rarst** [comment]
Fixed by 6677cf7dbe0123247ae9c8af5931f3808eb0c19a

Would you mind testing this please? I'll tag a release if all good. :)

**Comment by Rarst** [comment]
Fixed by 6677cf7dbe0123247ae9c8af5931f3808eb0c19a

Would you mind testing this please? I'll tag a release if all good. :)

**Comment by grappler** [comment]
I have updated our release-belt and `composer update` worked great! Thank you @Rarst!

**Pull request closed without merging**
